import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CurrentToolProvider } from "./contexts/CurrentTool";
import { PlacedObjectsProvider } from "./contexts/PlacedObjects";
import QueryProviders from "./contexts/ReactQuery";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Venue 3D Preview & Editor",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning className={"dark"}>
			<head>
				<script
					crossOrigin="anonymous"
					src="//unpkg.com/react-scan/dist/auto.global.js"
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Toaster position="top-left" richColors />
				<QueryProviders>
					<PlacedObjectsProvider>
						<CurrentToolProvider>{children}</CurrentToolProvider>
					</PlacedObjectsProvider>
				</QueryProviders>
			</body>
		</html>
	);
}
